In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

# Gender Analysis

Gender 0 for female & Gender 1 for male

In [22]:
batch = torch.load('temp/batch_0.pt')

In [23]:
batch

{'ID': tensor([467, 359, 421, 453, 349, 361, 384, 410, 442, 411, 337, 470, 332, 481,
         308, 384, 373, 311, 301, 410, 438, 359, 332, 314, 408, 431, 384, 323,
         359, 332, 314, 378, 332, 349, 337, 442, 405, 435, 311, 311, 334, 311,
         481, 384, 466, 332, 405, 359, 314, 442, 306, 308, 314, 309, 481, 308,
         435, 334, 349, 435, 435, 481, 337, 435, 311, 410, 359, 337, 359, 410,
         314, 481, 405, 387, 308, 462, 365, 337, 332, 435, 442, 337, 354, 442,
         332, 424, 411, 311, 306, 308, 387, 431, 384, 308, 300, 332, 384, 442,
         405, 469]),
 'gender_gt': tensor([1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0.,
         1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1.,
         0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
         1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1.,
         0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
  

In [24]:
# get each gender indices, numpy.ndarray
female_idx = np.where(batch['gender_gt']==0)[0]
male_idx = np.where(batch['gender_gt']==1)[0]

In [27]:
# get each gender GT
female_phq_binary_gt = batch['phq_binary_gt'][female_idx]
male_phq_binary_gt = batch['phq_binary_gt'][male_idx]

In [30]:
female_phq_binary_gt

tensor([1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
        1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0.,
        1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1.,
        0., 1., 0., 1., 1., 1., 0.])

In [33]:
num_female_total = len(female_phq_binary_gt)
num_female_depressed = len(np.where(female_phq_binary_gt==1)[0])
num_female_notdepressed = len(np.where(female_phq_binary_gt==0)[0])

num_female_total, num_female_depressed, num_female_notdepressed

(61, 35, 26)

In [ ]:
msg = ('  - Correlation:\n'
                   '      Spearman correlation: {0:8.6f}\n').format(rho)
log_and_print(base_logger, msg)

In [28]:
female_phq_binary_gt

tensor([1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
        1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0.,
        1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1.,
        0., 1., 0., 1., 1., 1., 0.])

In [29]:
male_phq_binary_gt

tensor([0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0.,
        1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1.,
        0., 1., 0.])

In [ ]:
columns = ['Participent ID', 'Binary GT', 'Final binary prediction', 'num_clips'] + ['clip_{:02}'.format(i+1) for i in range(20)]

In [38]:
id_clips_pred = np.zeros(10)
id_clips_pred[:] = None 
id_clips_pred[:5] = [1, 0, 1, 1, 0]

In [41]:
id_clips_pred[:5].sum()

3.0

In [42]:
int(5.5)

5