In [1]:
import numpy as np
import torch
import torch.nn as nn

# sum, mean, median, multiplication, concat, majority voting

# Sum

In [61]:
input1 = torch.randn(2, 128)
input2 = torch.randn(2, 128)
input3 = torch.randn(2, 128)

In [62]:
output = input1 + input2 + input3

In [63]:
output.shape

torch.Size([2, 128])

In [64]:
input1[0, :8], input2[0, :8], input3[0, :8], output[0, :8]

(tensor([ 0.4083, -0.4796, -0.8383,  1.3664,  0.8150, -1.1856,  0.0075, -0.2266]),
 tensor([0.3041, 0.4121, 1.1434, 1.2350, 0.7089, 0.7158, 0.9989, 1.0971]),
 tensor([-0.3913,  0.6618,  0.3074, -0.3041, -1.5659, -3.1922,  1.5595,  0.8624]),
 tensor([ 0.3211,  0.5943,  0.6125,  2.2972, -0.0420, -3.6620,  2.5659,  1.7329]))

# Mean

In [23]:
input1 = torch.randn(2, 128)
input2 = torch.randn(2, 128)
input3 = torch.randn(2, 128)

output = (input1 + input2 + input3) / 3

In [65]:
input1[0, :8], input2[0, :8], input3[0, :8], output[0, :8]

(tensor([ 0.4083, -0.4796, -0.8383,  1.3664,  0.8150, -1.1856,  0.0075, -0.2266]),
 tensor([0.3041, 0.4121, 1.1434, 1.2350, 0.7089, 0.7158, 0.9989, 1.0971]),
 tensor([-0.3913,  0.6618,  0.3074, -0.3041, -1.5659, -3.1922,  1.5595,  0.8624]),
 tensor([ 0.3211,  0.5943,  0.6125,  2.2972, -0.0420, -3.6620,  2.5659,  1.7329]))

# Median

In [66]:
input1 = torch.randn(2, 128)
input2 = torch.randn(2, 128)
input3 = torch.randn(2, 128)

output = torch.median(torch.stack([input1, input2, input3], axis=-1), dim=-1).values

In [67]:
input1[0, :8], input2[0, :8], input3[0, :8], output[0, :8]

(tensor([-0.0925,  0.6890,  0.8991, -0.4572, -0.1507,  0.3859,  1.0516,  1.1450]),
 tensor([-0.0080, -1.3823,  1.6848, -0.5771,  0.4616, -0.6396,  1.2812,  0.4066]),
 tensor([ 0.5534,  1.0167, -0.8309,  0.5735, -0.2075, -1.1470,  0.9102, -0.2691]),
 tensor([-0.0080,  0.6890,  0.8991, -0.4572, -0.1507, -0.6396,  1.0516,  0.4066]))

# Multiplication

In [52]:
input1 = torch.randn(2, 128)
input2 = torch.randn(2, 128)
input3 = torch.randn(2, 128)

output = input1 * input2 * input3

In [54]:
input1[0, :8], input2[0, :8], input3[0, :8], output[0, :8]

(tensor([ 2.4554, -0.9643,  0.9821,  0.1239, -0.5007,  0.4908, -3.3054, -0.8331]),
 tensor([-0.0352,  0.2774,  0.7817,  0.3312,  1.2934, -0.1818,  0.9694, -0.1265]),
 tensor([-1.3112,  0.3359,  0.4569,  1.6736, -0.2904,  1.0600,  1.1344,  1.7350]),
 tensor([ 0.1134, -0.0899,  0.3508,  0.0687,  0.1880, -0.0946, -3.6349,  0.1828]))

# Maximum

In [13]:
input1 = torch.randn(2, 128)
input2 = torch.randn(2, 128)
input3 = torch.randn(2, 128)

output = torch.stack([input1, input2, input3], axis=-1).max(dim=-1).values

In [14]:
input1[0, :8], input2[0, :8], input3[0, :8], output[0, :8]

(tensor([ 0.6940, -0.3635, -2.1909, -0.6600,  0.3839, -0.9171,  0.7914, -0.3492]),
 tensor([-1.1887, -1.0842,  0.4854, -0.2497, -0.1989, -2.0303, -1.7055, -0.6507]),
 tensor([ 0.4384, -0.1163, -0.4438,  0.0712, -1.3231,  0.9429,  0.9035,  0.4979]),
 tensor([ 0.6940, -0.1163,  0.4854,  0.0712,  0.3839,  0.9429,  0.9035,  0.4979]))

In [15]:
output.shape

torch.Size([2, 128])

# Concatenate

In [70]:
input1 = torch.randn(2, 128)
input2 = torch.randn(2, 128)
input3 = torch.randn(2, 128)

output = torch.cat([input1, input2, input3], dim=-1)

In [71]:
output.shape

torch.Size([2, 384])

# Attention Bottlenecks for Multimodal Fusion

form paper Attentional Feature Fusion from Dai et al.

Credential: code origiate from https://github.com/YimianDai/open-aff

In [39]:
exp_input = torch.stack([input1, input2, input1, input2, input1], dim=1)
B, H, W = exp_input.shape
print(exp_input.shape)

exp_input = exp_input.unsqueeze(dim=1)  # same as exp_input.view(B, 1, H, W)
print(exp_input.shape)

torch.Size([2, 5, 128])
torch.Size([2, 1, 5, 128])


In [46]:
conv2X2 = nn.Conv2d(64, 16, kernel_size=3, stride=1,
                    padding=1, groups=1, bias=False, dilation=1)

In [47]:
a = torch.randn([2, 64, 5, 128])

In [51]:
result = conv2X2(a)
result.shape

torch.Size([2, 16, 5, 128])

In [20]:
import torch
import torch.nn as nn


class DAF(nn.Module):
    '''
    直接相加 DirectAddFuse
    '''

    def __init__(self):
        super(DAF, self).__init__()

    def forward(self, x, residual):
        return x + residual


class iAFF(nn.Module):
    '''
    多特征融合 iAFF
    '''

    def __init__(self, channels=64, r=4):
        super(iAFF, self).__init__()
        inter_channels = int(channels // r)

        # 本地注意力
        self.local_att = nn.Sequential(
            nn.Conv2d(channels, inter_channels, kernel_size=1, stride=1, padding=0),
            nn.BatchNorm2d(inter_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(inter_channels, channels, kernel_size=1, stride=1, padding=0),
            nn.BatchNorm2d(channels),
        )

        # 全局注意力
        self.global_att = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Conv2d(channels, inter_channels, kernel_size=1, stride=1, padding=0),
            nn.BatchNorm2d(inter_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(inter_channels, channels, kernel_size=1, stride=1, padding=0),
            nn.BatchNorm2d(channels),
        )

        # 第二次本地注意力
        self.local_att2 = nn.Sequential(
            nn.Conv2d(channels, inter_channels, kernel_size=1, stride=1, padding=0),
            nn.BatchNorm2d(inter_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(inter_channels, channels, kernel_size=1, stride=1, padding=0),
            nn.BatchNorm2d(channels),
        )
        # 第二次全局注意力
        self.global_att2 = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Conv2d(channels, inter_channels, kernel_size=1, stride=1, padding=0),
            nn.BatchNorm2d(inter_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(inter_channels, channels, kernel_size=1, stride=1, padding=0),
            nn.BatchNorm2d(channels),
        )

        self.sigmoid = nn.Sigmoid()

    def forward(self, x, residual):
        xa = x + residual
        xl = self.local_att(xa)
        xg = self.global_att(xa)
        xlg = xl + xg
        wei = self.sigmoid(xlg)
        xi = x * wei + residual * (1 - wei)

        xl2 = self.local_att2(xi)
        xg2 = self.global_att(xi)
        xlg2 = xl2 + xg2
        wei2 = self.sigmoid(xlg2)
        xo = x * wei2 + residual * (1 - wei2)
        return xo


class AFF(nn.Module):
    '''
    多特征融合 AFF
    '''

    def __init__(self, channels=64, r=4):
        super(AFF, self).__init__()
        inter_channels = int(channels // r)

        self.local_att = nn.Sequential(
            nn.Conv2d(channels, inter_channels, kernel_size=1, stride=1, padding=0),
            nn.BatchNorm2d(inter_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(inter_channels, channels, kernel_size=1, stride=1, padding=0),
            nn.BatchNorm2d(channels),
        )

        self.global_att = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Conv2d(channels, inter_channels, kernel_size=1, stride=1, padding=0),
            nn.BatchNorm2d(inter_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(inter_channels, channels, kernel_size=1, stride=1, padding=0),
            nn.BatchNorm2d(channels),
        )

        self.sigmoid = nn.Sigmoid()

    def forward(self, x, residual):
        xa = x + residual
        xl = self.local_att(xa)
        xg = self.global_att(xa)
        xlg = xl + xg
        wei = self.sigmoid(xlg)

        xo = 2 * x * wei + 2 * residual * (1 - wei)
        return xo
    
    
def conv1x1(in_channels, out_channels, stride=1):
    """1x1 convolution"""
    return nn.Conv2d(in_channels, out_channels, kernel_size=1, stride=stride, bias=False)


def conv3x3(in_channels, out_channels, stride=1, groups=1, dilation=1):
    """3x3 convolution with padding"""
    return nn.Conv2d(in_channels, out_channels, kernel_size=3, stride=stride,
                     padding=dilation, groups=groups, bias=False, dilation=dilation)

def conv5x5(in_channels, out_channels, stride=1, groups=1, dilation=1):
    """5x5 convolution with padding"""
    return nn.Conv2d(in_channels, out_channels, kernel_size=5, stride=stride,
                     padding=2, groups=groups, bias=False, dilation=dilation)


class Bottleneck(nn.Module):
    # Bottleneck in torchvision places the stride for downsampling at 3x3 convolution(self.conv2)
    # while original implementation places the stride at the first 1x1 convolution(self.conv1)
    # according to "Deep residual learning for image recognition"https://arxiv.org/abs/1512.03385.
    # This variant is also known as ResNet V1.5 and improves accuracy according to
    # https://ngc.nvidia.com/catalog/model-scripts/nvidia:resnet_50_v1_5_for_pytorch.
    
    expansion = 16

    def __init__(self, inplanes, planes, base_width=64,
                 fuse_type='DAF', stride=1, groups=1, dilation=1):
        super(Bottleneck, self).__init__()
        
        norm_layer = nn.BatchNorm2d
        width = int(planes * (base_width / 64.)) * groups
        # Both self.conv2 and self.downsample layers downsample the input when stride != 1
        self.conv1 = conv1x1(inplanes, width)
        self.bn1 = norm_layer(width)
        self.conv2 = conv5x5(width, width, stride, groups, dilation)
        self.bn2 = norm_layer(width)
        self.conv3 = conv1x1(width, planes * self.expansion)
        self.bn3 = norm_layer(planes * self.expansion)
        self.conv4 = conv5x5(planes * self.expansion, width, stride, groups, dilation)
        self.bn4 = norm_layer(width)
        self.conv5 = conv1x1(width, inplanes)
        self.bn5 = norm_layer(inplanes)        
        
        self.relu = nn.ReLU(inplace=True)
        self.stride = stride

        if fuse_type == 'AFF':
            self.fuse_mode = AFF(channels=planes * self.expansion)
        elif fuse_type == 'iAFF':
            self.fuse_mode = iAFF(channels=planes * self.expansion)
        elif fuse_type == 'DAF':
            self.fuse_mode = DAF()
        else:
            self.fuse_mode = None
            
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
            elif isinstance(m, (nn.BatchNorm2d, nn.GroupNorm)):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)

    def forward(self, x):
        identity = x

        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)

        out = self.conv2(out)
        out = self.bn2(out)
        out = self.relu(out)

        out = self.conv3(out)
        out = self.bn3(out)

        # out += identity
        out = self.fuse_mode(out, identity)
        out = self.relu(out)
        
        out = self.conv4(out)
        out = self.bn4(out)
        out = self.relu(out)

        out = self.conv5(out)
        out = self.bn5(out)
        out = self.relu(out)
        
        return out


In [97]:
input1 = torch.randn(2, 128)
input2 = torch.randn(2, 128)
input3 = torch.randn(2, 128)

exp_input = torch.stack([input1, input2, input1, input3, input2], dim=1)
B, H, W = exp_input.shape
print(exp_input.shape)

exp_input = exp_input.unsqueeze(dim=1)  # same as exp_input.view(B, 1, H, W)
print(exp_input.shape)

torch.Size([2, 5, 128])
torch.Size([2, 1, 5, 128])


In [98]:
fusion_layer = Bottleneck(inplanes=1, planes=4, base_width=256, fuse_type='iAFF')

In [99]:
result = fusion_layer(exp_input)

In [100]:
result.shape

torch.Size([2, 1, 5, 128])

In [101]:
B, C, H, W = result.shape
result = result.view(B, -1)

result.shape

torch.Size([2, 640])

In [21]:
input1 = torch.randn(2, 128)
input2 = torch.randn(2, 128)
input3 = torch.randn(2, 128)

exp_input = torch.stack([input1, input2, input1, input3], dim=1)
B, H, W = exp_input.shape
print(exp_input.shape)

exp_input = exp_input.unsqueeze(dim=1)  # same as exp_input.view(B, 1, H, W)
print(exp_input.shape)

torch.Size([2, 4, 128])
torch.Size([2, 1, 4, 128])


In [22]:
fusion_layer = Bottleneck(inplanes=1, planes=4, base_width=256, fuse_type='iAFF')

In [23]:
result = fusion_layer(exp_input)

In [24]:
result.shape

torch.Size([2, 1, 4, 128])